---
title: "Fiddler crabs"
author: "Peter Menzies"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r, include = FALSE}
crabs <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize (1).csv"))
```

```{r, fig.alt = "Male fiddler crabs carapace width increases over 12 degrees of latitiude, with the data following a gradual positive linear correlation.", fig.show = "show", echo = FALSE}
#Create a plot of fiddler crab carapace widths observed at the different latitudes
#Finalize your figure, include a title and updated axis labels, add alt-text, and add a figure caption (you #can either do this in the code chunk options or just in plain markdown text below your figure). Update code chunk options so that only your finalized graph and figure caption show up in your knitted report (i.e., no code should show up, or you can use code folding)
#Push your updates

crab_plot <- ggplot(data = crabs, aes(x = Latitude, y = carapace_width)) +
  geom_point() +
  labs(x = "Latitude",
       y = "Carapace Width (mm)",
       title = "Carapace Width as a function of latitude on east coast",
       caption = "Do fiddler crabs follow Bergman's rule?")

crab_plot
```

```{r, alt.fig = "This scatterplot shows crab carapace width as a funtion of mean annual water temperature, displaying a negative linear correlation"}
water_temp_carapace <- ggplot(crabs, aes(x = MATW, y = carapace_width)) +
  geom_point(aes(color = MATW)) +
  labs(x = "Mean annual water temperature", y = "Carapace width (mm)", title = "Crab cararpce width vs mean annual water temperature", caption = "A negative linear correlation between water temperature and carapace width of fiddler crabs on the east coast")

water_temp_carapace
```

